#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ClientApp.Resource", IsApplication=true)]

namespace ClientApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050019
			public const int actualizarResultados = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int actualizarResultados2 = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int botonFin = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int botonLog = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int confirmar = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int confirmarFondos = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int continuarResultados = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int continuarResultados2 = 2131034143;
			
			// aapt resource value: 0x7f050013
			public const int passInput = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int seekBar = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int selector = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow1 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int tableRow2 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int textError = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int textGracias = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int textViewFPr = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int textViewFPu = 2131034121;
			
			// aapt resource value: 0x7f050020
			public const int textViewGananciasAcumuladas = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int textViewInstruccion = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int textViewNumResultados = 2131034139;
			
			// aapt resource value: 0x7f050012
			public const int textViewPassword = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int textViewResultados1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int textViewResultados2 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int textViewResultados3 = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int textViewResumen = 2131034141;
			
			// aapt resource value: 0x7f050003
			public const int textViewRonda = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int textViewRondaFondos = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int textViewTitle = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int textViewTitleFondos = 2131034119;
			
			// aapt resource value: 0x7f05001c
			public const int textViewTotalPublico = 2131034140;
			
			// aapt resource value: 0x7f05000f
			public const int textViewUsuario = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int usuarioInput = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AgradecimientoLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BeautyContestActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FondosLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ResultadosBeautyContestLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ResultadosFondosLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int Agradecimiento = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int HintPass = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int HintUsuario = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
